<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://soa.com/uri/products/ContainerStateService/wsdl/1.0" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://soa.com/uri/products/ContainerStateService/wsdl/1.0" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:nms1="http://soa.com/uri/products/ContainerState/xsd/1.0" xmlns:shttp="http://soa.com/wsdl/http">
  <wsdl:types>
    <xs:schema targetNamespace="http://soa.com/uri/products/ContainerState/xsd/1.0" version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:simpleType name="State"><xs:restriction base="xs:string"><xs:enumeration value="Started"/><xs:enumeration value="Shutdown"/><xs:enumeration value="Active"/></xs:restriction></xs:simpleType>
</xs:schema>
  </wsdl:types>
  <wsdl:message name="reportStateResponseMessage">
    <wsdl:part element="xs:any">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="reportStateRequestMessage">
    <wsdl:part name="key" type="xs:string">
    </wsdl:part>
    <wsdl:part name="parameter0" type="nms1:State">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="ContainerStateRESTPortType">
    <wsdl:operation name="reportState">
      <wsdl:input message="tns:reportStateRequestMessage">
    </wsdl:input>
      <wsdl:output message="tns:reportStateResponseMessage">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="ContainerStateRESTBinding" type="tns:ContainerStateRESTPortType">
    <shttp:binding/>
    <wsdl:operation name="reportState">
<wsdl:documentation><sdoc:displayName xmlns:sdoc="http://soa.com/wsdl/doc">PUT /{key}/state</sdoc:displayName><sdoc:description xmlns:sdoc="http://soa.com/wsdl/doc"><![CDATA[<p>Reports the state of the specified container. The following example illustrates reporting container 24141ffe-8954-4adf-9a2f-30b2054c has started.</p><p>Request:<br>PUT /rest/containers/24141ffe-8954-4adf-9a2f-30b2054c/state HTTP/1.1<br>"Started"</p><p>Response:<br/>HTTP/1.1 200 OK</p>]]></sdoc:description><sdoc:summary xmlns:sdoc="http://soa.com/wsdl/doc"><![CDATA[Report State]]></sdoc:summary><sdoc:response code="200" xmlns:sdoc="http://soa.com/wsdl/doc"><sdoc:description><![CDATA[Success]]></sdoc:description></sdoc:response><sdoc:response code="404" xmlns:sdoc="http://soa.com/wsdl/doc"><sdoc:description><![CDATA[Specified container not found (Invalid key)]]></sdoc:description></sdoc:response></wsdl:documentation>
    <shttp:operation inputSerialization="application/xml,application/json" location="/{key}/state" method="PUT"/>
      <wsdl:input>
    <shttp:input name="key" part="key" type="path"><wsdl:documentation><sdoc:description xmlns:sdoc="http://soa.com/wsdl/doc"><![CDATA[The container key]]></sdoc:description><sdoc:required xmlns:sdoc="http://soa.com/wsdl/doc">true</sdoc:required><sdoc:multiple xmlns:sdoc="http://soa.com/wsdl/doc">false</sdoc:multiple></wsdl:documentation></shttp:input>
    <shttp:input name="parameter0" part="parameter0" type="entity"><wsdl:documentation><sdoc:description xmlns:sdoc="http://soa.com/wsdl/doc"><![CDATA[The current state]]></sdoc:description><sdoc:required xmlns:sdoc="http://soa.com/wsdl/doc">true</sdoc:required><sdoc:multiple xmlns:sdoc="http://soa.com/wsdl/doc">false</sdoc:multiple></wsdl:documentation></shttp:input>
      </wsdl:input>
      <wsdl:output>
    <shttp:output name="" part="" type="entity"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="ContainerStateREST">
<wsdl:documentation><sdoc:description xmlns:sdoc="http://soa.com/wsdl/doc"><![CDATA[This API is used to report container state to Policy Manager.]]></sdoc:description><sdoc:title xmlns:sdoc="http://soa.com/wsdl/doc">Container State Reporting API</sdoc:title><sdoc:version xmlns:sdoc="http://soa.com/wsdl/doc">8.0.0</sdoc:version><sdoc:vendor xmlns:sdoc="http://soa.com/wsdl/doc">SOA Software</sdoc:vendor></wsdl:documentation>
    <wsdl:port name="ContainerStateREST_rest_port_https" binding="tns:ContainerStateRESTBinding">
    <shttp:address location="https://0.0.0.0/rest/containers"/>
    </wsdl:port>
    <wsdl:port name="ContainerStateREST_rest_port_http" binding="tns:ContainerStateRESTBinding">
    <shttp:address location="http://0.0.0.0/rest/containers"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
