<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="urn:com.soa.assetgraph.api" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="urn:com.soa.assetgraph.api" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:shttp="http://soa.com/wsdl/http">
  <wsdl:message name="getAssetGraphRequestMessage">
    <wsdl:part name="AssetID" type="xs:string">
    </wsdl:part>
    <wsdl:part name="AssetType" type="xs:string">
    </wsdl:part>
    <wsdl:part name="GraphType" type="xs:string">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="getAssetGraphResponseMessage">
    <wsdl:part name="getAssetGraphResponse" type="tns:List">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="AssetGraphAPIPortType">
    <wsdl:operation name="getAssetGraph">
      <wsdl:input message="tns:getAssetGraphRequestMessage">
    </wsdl:input>
      <wsdl:output message="tns:getAssetGraphResponseMessage">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="AssetGraphAPIBinding" type="tns:AssetGraphAPIPortType">
    <shttp:binding/>
    <wsdl:operation name="getAssetGraph">
<wsdl:documentation><sdoc:displayName xmlns:sdoc="http://soa.com/wsdl/doc">GET /assetgraphs/{AssetID}</sdoc:displayName></wsdl:documentation>
    <shttp:operation location="/assetgraphs/{AssetID}" method="GET" outputSerialization="application/json,application/vnd.soa.v84+json"/>
      <wsdl:input>
    <shttp:input name="AssetID" part="AssetID" type="path"><wsdl:documentation><sdoc:description xmlns:sdoc="http://soa.com/wsdl/doc"><![CDATA[The asset's Id.]]></sdoc:description><sdoc:required xmlns:sdoc="http://soa.com/wsdl/doc">false</sdoc:required><sdoc:multiple xmlns:sdoc="http://soa.com/wsdl/doc">false</sdoc:multiple></wsdl:documentation></shttp:input>
    <shttp:input name="AssetType" part="AssetType" type="query"><wsdl:documentation><sdoc:description xmlns:sdoc="http://soa.com/wsdl/doc"><![CDATA[The asset type]]></sdoc:description><sdoc:required xmlns:sdoc="http://soa.com/wsdl/doc">true</sdoc:required><sdoc:multiple xmlns:sdoc="http://soa.com/wsdl/doc">false</sdoc:multiple></wsdl:documentation></shttp:input>
    <shttp:input name="GraphType" part="GraphType" type="query"><wsdl:documentation><sdoc:description xmlns:sdoc="http://soa.com/wsdl/doc"><![CDATA[Type of graph]]></sdoc:description><sdoc:required xmlns:sdoc="http://soa.com/wsdl/doc">true</sdoc:required><sdoc:multiple xmlns:sdoc="http://soa.com/wsdl/doc">false</sdoc:multiple></wsdl:documentation></shttp:input>
      </wsdl:input>
      <wsdl:output>
    <shttp:output name="getAssetGraphResponse" part="getAssetGraphResponse" type="entity"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="AssetGraphAPI">
<wsdl:documentation><sdoc:description xmlns:sdoc="http://soa.com/wsdl/doc"><![CDATA[The API for returning graphs of assets and their relationships to each other.]]></sdoc:description><sdoc:title xmlns:sdoc="http://soa.com/wsdl/doc">Asset Graph API</sdoc:title><sdoc:version xmlns:sdoc="http://soa.com/wsdl/doc">8.4.0</sdoc:version><sdoc:vendor xmlns:sdoc="http://soa.com/wsdl/doc">Rogue Wave Software</sdoc:vendor></wsdl:documentation>
    <wsdl:port name="AssetGraphAPI_rest_port_http" binding="tns:AssetGraphAPIBinding">
    <shttp:address location="http://0.0.0.0/api"/>
    </wsdl:port>
    <wsdl:port name="AssetGraphAPI_rest_port_https" binding="tns:AssetGraphAPIBinding">
    <shttp:address location="https://0.0.0.0/api"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
