<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="urn:com.soa.tenant.admin.impl" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="urn:com.soa.tenant.admin.impl" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:shttp="http://soa.com/wsdl/http">
  <wsdl:message name="addTenantRequestMessage">
    <wsdl:part name="FedMemderId" type="xs:string">
    </wsdl:part>
    <wsdl:part name="TenantName" type="xs:string">
    </wsdl:part>
    <wsdl:part name="Address" type="xs:string">
    </wsdl:part>
    <wsdl:part name="ConsoleAddress" type="xs:string">
    </wsdl:part>
    <wsdl:part name="Theme" type="xs:string">
    </wsdl:part>
    <wsdl:part name="ThemeImpl" type="xs:string">
    </wsdl:part>
    <wsdl:part name="ESIndexName" type="xs:string">
    </wsdl:part>
    <wsdl:part name="ContactEmailAddress" type="xs:string">
    </wsdl:part>
    <wsdl:part name="FromEmailAddress" type="xs:string">
    </wsdl:part>
    <wsdl:part name="Email" type="xs:string">
    </wsdl:part>
    <wsdl:part name="Password" type="xs:string">
    </wsdl:part>
    <wsdl:part name="VirtualHosts" type="xs:string">
    </wsdl:part>
    <wsdl:part name="FwdProxyAllowedHosts" type="xs:string">
    </wsdl:part>
    <wsdl:part name="CName" type="xs:string">
    </wsdl:part>
    <wsdl:part name="CDNRoot" type="xs:string">
    </wsdl:part>
    <wsdl:part name="DocumentDomain" type="xs:string">
    </wsdl:part>
    <wsdl:part name="OrgKey" type="xs:string">
    </wsdl:part>
    <wsdl:part name="LaasSupport" type="xs:string">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="addTenantResponseMessage">
    <wsdl:part name="addTenantResponse" type="xs:string">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="TenantCreationAPIPortType">
    <wsdl:operation name="addTenant">
      <wsdl:input message="tns:addTenantRequestMessage">
    </wsdl:input>
      <wsdl:output message="tns:addTenantResponseMessage">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="TenantCreationAPIBinding" type="tns:TenantCreationAPIPortType">
    <shttp:binding/>
    <wsdl:operation name="addTenant">
<wsdl:documentation><sdoc:displayName xmlns:sdoc="http://soa.com/wsdl/doc">POST /tenants</sdoc:displayName></wsdl:documentation>
    <shttp:operation inputSerialization="application/x-www-form-urlencoded" location="/tenants" method="POST" outputSerialization="text/plain"/>
      <wsdl:input>
    <shttp:input name="FedMemderId" part="FedMemderId" type="query"/>
    <shttp:input name="TenantName" part="TenantName" type="query"/>
    <shttp:input name="Address" part="Address" type="query"/>
    <shttp:input name="ConsoleAddress" part="ConsoleAddress" type="query"/>
    <shttp:input name="Theme" part="Theme" type="query"/>
    <shttp:input name="ThemeImpl" part="ThemeImpl" type="query"/>
    <shttp:input name="ESIndexName" part="ESIndexName" type="query"/>
    <shttp:input name="ContactEmailAddress" part="ContactEmailAddress" type="query"/>
    <shttp:input name="FromEmailAddress" part="FromEmailAddress" type="query"/>
    <shttp:input name="Email" part="Email" type="query"/>
    <shttp:input name="Password" part="Password" type="query"/>
    <shttp:input name="VirtualHosts" part="VirtualHosts" type="query"/>
    <shttp:input name="FwdProxyAllowedHosts" part="FwdProxyAllowedHosts" type="query"/>
    <shttp:input name="CName" part="CName" type="query"/>
    <shttp:input name="CDNRoot" part="CDNRoot" type="query"/>
    <shttp:input name="DocumentDomain" part="DocumentDomain" type="query"/>
    <shttp:input name="OrgKey" part="OrgKey" type="query"/>
    <shttp:input name="LaasSupport" part="LaasSupport" type="query"/>
      </wsdl:input>
      <wsdl:output>
    <shttp:output name="addTenantResponse" part="addTenantResponse" type="entity"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="TenantCreationAPI">
<wsdl:documentation><sdoc:title xmlns:sdoc="http://soa.com/wsdl/doc">Tenant Creation API</sdoc:title><sdoc:description xmlns:sdoc="http://soa.com/wsdl/doc"><![CDATA[<p>A simple service that allows tenants to be created.</p>]]></sdoc:description></wsdl:documentation>
    <wsdl:port name="TenantCreationAPI_rest_port_https" binding="tns:TenantCreationAPIBinding">
    <shttp:address location="https://0.0.0.0/api"/>
    </wsdl:port>
    <wsdl:port name="TenantCreationAPI_rest_port_http" binding="tns:TenantCreationAPIBinding">
    <shttp:address location="http://0.0.0.0/api"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
