#%RAML 0.8
title: Aria Object Query API
baseUri: https://secure.current.stage.ariasystems.net/api/AriaQuery/objects.php
version: v1
/:
  displayName: ObjectQuery
  post:
    description: |
      Query Aria
    body:
      text/plain:
    responses:
      200:
        body:
          application/json:
