#!/bin/bash
# $id$

if [ $# -eq 0 ]
  then
    echo "Merge data size (# of hours) must be specified"
fi

DB_USER=""
DB_PASS=""
DB_NAME=""

mysqlcmd="mysql -NB -u $DB_USER -p${DB_PASS} -D $DB_NAME -e "
STARTTIME=`$mysqlcmd "SELECT MIN(REQUESTDTS) FROM MO_USAGEDATA"`
[ $? != 0 ] && { echo "cannot connect to database"; exit 1; }
ENDTIME=`$mysqlcmd "SELECT MAX(REQUESTDTS) FROM MO_USAGEDATA"`


MSGSCMD1="INSERT INTO MO_USAGEMSGS SELECT * FROM MO_USAGEMSGS_BCK where MSGCAPTUREDDTS between X and Y;"
DATACMD1="INSERT INTO MO_USAGEDATA (EVENTID PARENTEVENTID CLIENTHOST MPNAME OPERATIONID SERVICEID ORGID CONTRACTID BINDTEMPLATEID REQUSERNAME REQUESTDTS REQUESTMILLIS RESPONSETIME REQMSGSIZE NMREQMSGSIZE RESPMSGSIZE NMRESPMSGSIZE ERRCATEGORY ERRMESSAGE ERRDETAILS CREATEDTS CREATEDMILLIS NEXTHOPURL ISSOAPFLTBYMP ISSOAPFLTBYNEXTHOP LISTENERURL NEXTHOPRESPTIME APPUSERNAME OTHERUSERNAMES CUSTOMFIELD1 VERB STATUS_CODE) SELECT EVENTID PARENTEVENTID CLIENTHOST MPNAME OPERATIONID SERVICEID ORGID CONTRACTID BINDTEMPLATEID REQUSERNAME REQUESTDTS REQUESTMILLIS RESPONSETIME REQMSGSIZE NMREQMSGSIZE RESPMSGSIZE NMRESPMSGSIZE ERRCATEGORY ERRMESSAGE ERRDETAILS CREATEDTS CREATEDMILLIS NEXTHOPURL ISSOAPFLTBYMP ISSOAPFLTBYNEXTHOP LISTENERURL NEXTHOPRESPTIME APPUSERNAME OTHERUSERNAMES CUSTOMFIELD1 VERB STATUS_CODE FROM MO_USAGEDATA_BCK where REQUESTDTS between X and Y;"
HOPCMD1="INSERT INTO MO_USAGE_NEXTHOP (EVENTID, URL, REQUESTDTS, CREATEDTS, RESPTIME) SELECT EVENTID, URL, REQUESTDTS, CREATEDTS, RESPTIME FROM MO_USAGE_NEXTHOP_BCK where REQUESTDTS between X and Y;"

$mysqlcmd "$MSGSCMD1"
[ $? != 0 ] && { echo "merge data failed; $MSGSCMD1"; exit 1; } || { echo "Successfully ran $MSGSCMD1"; }
$mysqlcmd "$DATACMD1"
[ $? != 0 ] && { echo "merge data failed; $DATACMD1"; exit 1; } || { echo "Successfully ran $DATACMD1"; }
$mysqlcmd "$HOPCMD1"
[ $? != 0 ] && { echo "merge data failed; $HOPCMD1"; exit 1; } || { echo "Successfully ran $HOPCMD1"; }

exit 0